### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by pligor** [robrich/gulp-rimraf#18]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, lstat '/home/pligor/projects/pligor.com/pligor/dist/bower_components/marionette'
```
Does the above makes any sense? We have no idea how to fix it
Could you help?

**Comment by robrich** [comment]
It means the thing you're trying to delete is already gone.

**Comment by pligor** [comment]
Hm... that's strange because the files were not erased at all, they were still present...

We were trying to do something like this:
```
return gulp.src(dirs.dist + "/**/*", {read: false}).pipe(
        gulpRimraf({
            force: false    //false means not outside of current working dir
        })
    )
```
but it failed

This `return rimraf(dirs.dist + "/", cb)` succeeds but erases the folder itself.

The goal is to delete all the contents of the folder and not the folder itself.

Any ideas?

**Comment by robrich** [comment]
You're right. I jumped to conclusions. It means it couldn't read the file
which often means it's already gone but also may mean you don't have
permission to the file because of something like a virus scanner looking at
it.
