### ISSUE TITLE
Deprecated status misleading since del doesn't support base

### ISSUE THREAD

**Issue by breyed** [robrich/gulp-rimraf#20]
The [Gulp page for rimraf](https://www.npmjs.com/package/gulp-rimraf) says that `rimraf` is deprecated. It refers to a recipe that tells how to use `del`. However, `del` doesn't support the `base` option, like `gulp.src` does. This makes `rimraf` still useful - usefulness that might be overlooked if a developer ignores rimraf, which is typically what you do for API calls that are deprecated.

**Comment by robrich** [comment]
Intriguing use case. Do you have an example task that couldn't use del
because of the missing base option?

**Comment by breyed** [comment]
I'm using the Visual Studio 2015 integrated task runner. It has pwd at the project level, but all the web files are under `wwwroot`. To avoid have to prefix everything with `wwwroot`, I wrap `gulp.src` and `gulp.dest` like this:

    function src(cwd, path) { return gulp.src(path, { cwd: join(project.wwwroot, cwd) }); }
    function dest(path) { return gulp.dest(path, { cwd: join(project.wwwroot) }); }

A sample task looks like this:

	gulp.task('min:css', ['sass'], function () {
		src('styles', '**/*.css')
			.pipe(concat(paths.min_css))
			.pipe(cssmin())
			.pipe(dest('build'));
	});

I ended up choosing `gulp-clean` for deletion. This is where I'd use `del` if I could:

	gulp.task('clean', function () {
		src([paths.min_css, paths.min_js])
			.pipe(clean());
	});

**Comment by breyed** [comment]
Looking back at the [Delete files and folders] article (and having a better understanding of gulp now), it looks like I can use `.pipe(vinylPaths(del))` instead, and so delete plugins indeed aren't necessary.
