### ISSUE TITLE
Odd issues when running rimraf as a dependency

### ISSUE THREAD

**Issue by aaronbushnell** [robrich/gulp-rimraf#7]
I'm running a clean task to remove a `_tmp` directory just before my `gulp.run('scss', 'coffee', 'js')` task recreates the directory. I'm getting an odd workflow error when running rimraf as a dependency on the default gulp task.

When I run `gulp` the `_tmp` directory is created by my `gulp.run('scss', 'coffee', 'js')` task. When I run `gulp` again, the `_tmp` directory is removed, but the `gulp.run('scss', 'coffee', 'js')` task isn't recreating it. Every time I run `gulp` I'm repeating these two processes until I occasionally receive this error:

``` sh
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/Users/[USERNAME]/Desktop/proj/app/_tmp/stylesheets/styles.css'
```

My gulpfile:

``` js
var gulp       = require('gulp');
var sass       = require('gulp-sass');
var prefix     = require('gulp-autoprefixer');
var coffee     = require('gulp-coffee');
var clean      = require('gulp-rimraf');

gulp.task('clean', function() {
    gulp.src('app/_tmp')
        .pipe(clean());
});

gulp.task('scss', function () {
    gulp.src('app/stylesheets/{,*/}*.scss')
        .pipe(sass())
        .pipe(prefix())
        .pipe(gulp.dest('app/_tmp/stylesheets'));
});

gulp.task('js', function () {
    gulp.src('app/javascripts/{,*/}*.js')
        .pipe(gulp.dest('app/_tmp/javascripts'));
});

gulp.task('coffee', function () {
    gulp.src('app/javascripts/{,*/}*.coffee')
        .pipe(coffee())
        .pipe(gulp.dest('app/_tmp/javascripts'));
});

gulp.task('default', ['clean'], function() {
    gulp.run('scss', 'coffee', 'js');

    gulp.watch('app/stylesheets/{,*/}*.scss', function() {
        gulp.run('scss');
    });

    gulp.watch('app/javascripts/*.js', function() {
        gulp.run('js');
    });

    gulp.watch('app/javascripts/*.coffee', function() {
        gulp.run('coffee');
    });
});
```

gulp info:

``` sh
[gulp] CLI version 3.3.4
[gulp] Local version 3.3.4
```

**Comment by DasJott** [comment]
Problem still exists for me.  Got the version from npm and enter this problem all the time.
I wonder this is closed...

**Comment by robrich** [comment]
Das, can you post a gulpfile?

**Comment by DasJott** [comment]
Sorry for responding so late.
This is, what VSCode shows in the Output window:

[15:18:05] Using gulpfile ~/workspace/code/HelloMvc/gulpfile.js
[15:18:05] Starting 'compileLess'...
[15:18:05] Starting 'clean'...
[15:18:06] Finished 'compileLess' after 789 ms
[15:18:06] Finished 'clean' after 780 ms
[15:18:06] Starting 'bundle'...
[15:18:06] Bundle 'base.scripts' using Content/js/jquery-2.2.0.js
[15:18:08] Copy file Content/img/DasJott_Fancy.png
[15:18:08] Copy file Content/fonts/glyphicons-halflings-regular.eot
[15:18:08] Bundle 'base.styles' using Content/css/main.css
[15:18:09] Bundle 'base.scripts' using Content/js/bootstrap.js
[15:18:10] Copy file Content/img/chosen-sprite.png
[15:18:10] Copy file Content/fonts/glyphicons-halflings-regular.svg
[15:18:10] Bundle 'base.scripts' using Content/js/bootbox.js
[15:18:10] Copy file Content/fonts/glyphicons-halflings-regular.ttf
[15:18:10] Bundle 'base.scripts' using Content/js/LoadSpinner.js
[15:18:10] Copy file Content/fonts/glyphicons-halflings-regular.woff
[15:18:10] Bundle 'base.scripts' using Content/js/main.js
[15:18:10] Copy file Content/fonts/glyphicons-halflings-regular.woff2
[15:18:10] Finished 'bundle' after 3.66 s
[15:18:10] Starting 'watch'...
[15:18:10] Finished 'watch' after 14 ms
[15:18:10] Starting 'default'...
[15:18:10] Finished 'default' after 6.82 μs
[15:50:14] Starting 'compileLess'...
[15:50:15] Finished 'compileLess' after 741 ms
[15:50:15] Starting 'clean'...
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, lstat '/home/dasjott/workspace/code/HelloMvc/wwwroot/fonts/glyphicons-halflings-regular.woff2'

Watching build tasks has finished.

[gulpfile.js.zip](https://github.com/robrich/gulp-rimraf/files/95666/gulpfile.js.zip)

**Comment by robrich** [comment]
Watch starts a new gulp runner, so it re-executes all the dependencies.  Did you want bundle to run clean on every change?

**Comment by DasJott** [comment]
Yes, I want to clean up, before bundle.
Am 20.01.2016 03:00 schrieb "Rob Richardson" <notifications@github.com>:

**Comment by robrich** [comment]
Then it looks like it's functioning as designed. What's the part that
surprised you?

**Comment by DasJott** [comment]
The error and the abortion of the build process annoys me.
What could be a solution for me here?
Am 22.01.2016 16:53 schrieb "Rob Richardson" <notifications@github.com>:

**Comment by robrich** [comment]
Ah, I see. It tried to clean in preparation for the next bundle run while
the previous bundle run was still running. Google for debounce. It'll wait
longer between runs when an event would otherwise repeat very quickly.

**Comment by DasJott** [comment]
You mean the error occurs only if a watch is triggered while a bundle is
still running?
Habe to try that soon...
Am 23.01.2016 3:27 nachm. schrieb "Rob Richardson" <notifications@github.com
>:

> Ah, I see. It tried to clean in preparation for the next bundle run while
> the previous bundle run was still running. Google for debounce. It'll wait
> longer between runs when an event would otherwise repeat very quickly.
